# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x0brpc_package\"\x1f\n\rCommonRequest\x12\x0e\n\x06signal\x18\x01 \x01(\x05\"\x1d\n\x0b\x43ommonReply\x12\x0e\n\x06signal\x18\x01 \x01(\x05\"\x1f\n\nResetReply\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"\xc9\x01\n\x15SamplerInitParamReply\x12\x12\n\nnum_joints\x18\x01 \x01(\x05\x12\x0f\n\x07obs_dim\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x63t_dim\x18\x03 \x01(\x05\x12\x14\n\x0c\x61\x63tor_hidden\x18\x04 \x03(\x05\x12\x15\n\rcritic_hidden\x18\x05 \x03(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\r\n\x05gamma\x18\x07 \x01(\x02\x12\x0f\n\x07lammbda\x18\x08 \x01(\x02\x12\x19\n\x11max_episode_steps\x18\t \x01(\x05\"F\n\x1bSampler2LearnerModelRequest\x12\x13\n\x0b\x61\x63tor_index\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x05\">\n\x19Sampler2LearnerModelReply\x12\x12\n\ntime_stamp\x18\x01 \x01(\x05\x12\r\n\x05model\x18\x02 \x01(\x0c\"T\n\x12SamplerDataRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ompressed_data\x18\x03 \x01(\x0c\"9\n\x14SamplerResultRequest\x12\x0f\n\x07rewards\x18\x01 \x03(\x02\x12\x10\n\x08path_len\x18\x02 \x03(\x02\x32W\n\x10HeartbeatService\x12\x43\n\tHeartBeat\x12\x1a.rpc_package.CommonRequest\x1a\x18.rpc_package.CommonReply\"\x00\x32X\n\x0cResetService\x12H\n\x0fget_reset_param\x12\x1a.rpc_package.CommonRequest\x1a\x17.rpc_package.ResetReply\"\x00\x32m\n\x17SamplerInitParamService\x12R\n\x0eget_init_param\x12\x1a.rpc_package.CommonRequest\x1a\".rpc_package.SamplerInitParamReply\"\x00\x32~\n\x1bSampler2LearnerModelService\x12_\n\tget_model\x12(.rpc_package.Sampler2LearnerModelRequest\x1a&.rpc_package.Sampler2LearnerModelReply\"\x00\x32^\n\x12SamplerDataService\x12H\n\tsend_data\x12\x1f.rpc_package.SamplerDataRequest\x1a\x18.rpc_package.CommonReply\"\x00\x32\x64\n\x14SamplerResultService\x12L\n\x0bsend_result\x12!.rpc_package.SamplerResultRequest\x1a\x18.rpc_package.CommonReply\"\x00\x62\x06proto3'
)




_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='rpc_package.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='rpc_package.CommonRequest.signal', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=58,
)


_COMMONREPLY = _descriptor.Descriptor(
  name='CommonReply',
  full_name='rpc_package.CommonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='rpc_package.CommonReply.signal', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=89,
)


_RESETREPLY = _descriptor.Descriptor(
  name='ResetReply',
  full_name='rpc_package.ResetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='rpc_package.ResetReply.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=122,
)


_SAMPLERINITPARAMREPLY = _descriptor.Descriptor(
  name='SamplerInitParamReply',
  full_name='rpc_package.SamplerInitParamReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_joints', full_name='rpc_package.SamplerInitParamReply.num_joints', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obs_dim', full_name='rpc_package.SamplerInitParamReply.obs_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_dim', full_name='rpc_package.SamplerInitParamReply.act_dim', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actor_hidden', full_name='rpc_package.SamplerInitParamReply.actor_hidden', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='critic_hidden', full_name='rpc_package.SamplerInitParamReply.critic_hidden', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='rpc_package.SamplerInitParamReply.batch_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='rpc_package.SamplerInitParamReply.gamma', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lammbda', full_name='rpc_package.SamplerInitParamReply.lammbda', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_episode_steps', full_name='rpc_package.SamplerInitParamReply.max_episode_steps', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=326,
)


_SAMPLER2LEARNERMODELREQUEST = _descriptor.Descriptor(
  name='Sampler2LearnerModelRequest',
  full_name='rpc_package.Sampler2LearnerModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actor_index', full_name='rpc_package.Sampler2LearnerModelRequest.actor_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='rpc_package.Sampler2LearnerModelRequest.time_stamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=398,
)


_SAMPLER2LEARNERMODELREPLY = _descriptor.Descriptor(
  name='Sampler2LearnerModelReply',
  full_name='rpc_package.Sampler2LearnerModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='rpc_package.Sampler2LearnerModelReply.time_stamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='rpc_package.Sampler2LearnerModelReply.model', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=462,
)


_SAMPLERDATAREQUEST = _descriptor.Descriptor(
  name='SamplerDataRequest',
  full_name='rpc_package.SamplerDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='rpc_package.SamplerDataRequest.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='rpc_package.SamplerDataRequest.time_stamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compressed_data', full_name='rpc_package.SamplerDataRequest.compressed_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=548,
)


_SAMPLERRESULTREQUEST = _descriptor.Descriptor(
  name='SamplerResultRequest',
  full_name='rpc_package.SamplerResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rewards', full_name='rpc_package.SamplerResultRequest.rewards', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path_len', full_name='rpc_package.SamplerResultRequest.path_len', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=607,
)

DESCRIPTOR.message_types_by_name['CommonRequest'] = _COMMONREQUEST
DESCRIPTOR.message_types_by_name['CommonReply'] = _COMMONREPLY
DESCRIPTOR.message_types_by_name['ResetReply'] = _RESETREPLY
DESCRIPTOR.message_types_by_name['SamplerInitParamReply'] = _SAMPLERINITPARAMREPLY
DESCRIPTOR.message_types_by_name['Sampler2LearnerModelRequest'] = _SAMPLER2LEARNERMODELREQUEST
DESCRIPTOR.message_types_by_name['Sampler2LearnerModelReply'] = _SAMPLER2LEARNERMODELREPLY
DESCRIPTOR.message_types_by_name['SamplerDataRequest'] = _SAMPLERDATAREQUEST
DESCRIPTOR.message_types_by_name['SamplerResultRequest'] = _SAMPLERRESULTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonRequest = _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.CommonRequest)
  })
_sym_db.RegisterMessage(CommonRequest)

CommonReply = _reflection.GeneratedProtocolMessageType('CommonReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.CommonReply)
  })
_sym_db.RegisterMessage(CommonReply)

ResetReply = _reflection.GeneratedProtocolMessageType('ResetReply', (_message.Message,), {
  'DESCRIPTOR' : _RESETREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.ResetReply)
  })
_sym_db.RegisterMessage(ResetReply)

SamplerInitParamReply = _reflection.GeneratedProtocolMessageType('SamplerInitParamReply', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERINITPARAMREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.SamplerInitParamReply)
  })
_sym_db.RegisterMessage(SamplerInitParamReply)

Sampler2LearnerModelRequest = _reflection.GeneratedProtocolMessageType('Sampler2LearnerModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLER2LEARNERMODELREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.Sampler2LearnerModelRequest)
  })
_sym_db.RegisterMessage(Sampler2LearnerModelRequest)

Sampler2LearnerModelReply = _reflection.GeneratedProtocolMessageType('Sampler2LearnerModelReply', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLER2LEARNERMODELREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.Sampler2LearnerModelReply)
  })
_sym_db.RegisterMessage(Sampler2LearnerModelReply)

SamplerDataRequest = _reflection.GeneratedProtocolMessageType('SamplerDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERDATAREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.SamplerDataRequest)
  })
_sym_db.RegisterMessage(SamplerDataRequest)

SamplerResultRequest = _reflection.GeneratedProtocolMessageType('SamplerResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERRESULTREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.SamplerResultRequest)
  })
_sym_db.RegisterMessage(SamplerResultRequest)



_HEARTBEATSERVICE = _descriptor.ServiceDescriptor(
  name='HeartbeatService',
  full_name='rpc_package.HeartbeatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=609,
  serialized_end=696,
  methods=[
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='rpc_package.HeartbeatService.HeartBeat',
    index=0,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEARTBEATSERVICE)

DESCRIPTOR.services_by_name['HeartbeatService'] = _HEARTBEATSERVICE


_RESETSERVICE = _descriptor.ServiceDescriptor(
  name='ResetService',
  full_name='rpc_package.ResetService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=698,
  serialized_end=786,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_reset_param',
    full_name='rpc_package.ResetService.get_reset_param',
    index=0,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_RESETREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESETSERVICE)

DESCRIPTOR.services_by_name['ResetService'] = _RESETSERVICE


_SAMPLERINITPARAMSERVICE = _descriptor.ServiceDescriptor(
  name='SamplerInitParamService',
  full_name='rpc_package.SamplerInitParamService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=788,
  serialized_end=897,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_init_param',
    full_name='rpc_package.SamplerInitParamService.get_init_param',
    index=0,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_SAMPLERINITPARAMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLERINITPARAMSERVICE)

DESCRIPTOR.services_by_name['SamplerInitParamService'] = _SAMPLERINITPARAMSERVICE


_SAMPLER2LEARNERMODELSERVICE = _descriptor.ServiceDescriptor(
  name='Sampler2LearnerModelService',
  full_name='rpc_package.Sampler2LearnerModelService',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=899,
  serialized_end=1025,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_model',
    full_name='rpc_package.Sampler2LearnerModelService.get_model',
    index=0,
    containing_service=None,
    input_type=_SAMPLER2LEARNERMODELREQUEST,
    output_type=_SAMPLER2LEARNERMODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLER2LEARNERMODELSERVICE)

DESCRIPTOR.services_by_name['Sampler2LearnerModelService'] = _SAMPLER2LEARNERMODELSERVICE


_SAMPLERDATASERVICE = _descriptor.ServiceDescriptor(
  name='SamplerDataService',
  full_name='rpc_package.SamplerDataService',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1027,
  serialized_end=1121,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_data',
    full_name='rpc_package.SamplerDataService.send_data',
    index=0,
    containing_service=None,
    input_type=_SAMPLERDATAREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLERDATASERVICE)

DESCRIPTOR.services_by_name['SamplerDataService'] = _SAMPLERDATASERVICE


_SAMPLERRESULTSERVICE = _descriptor.ServiceDescriptor(
  name='SamplerResultService',
  full_name='rpc_package.SamplerResultService',
  file=DESCRIPTOR,
  index=5,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1123,
  serialized_end=1223,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_result',
    full_name='rpc_package.SamplerResultService.send_result',
    index=0,
    containing_service=None,
    input_type=_SAMPLERRESULTREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLERRESULTSERVICE)

DESCRIPTOR.services_by_name['SamplerResultService'] = _SAMPLERRESULTSERVICE

# @@protoc_insertion_point(module_scope)
